AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'spec/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - Gemfile
    - Rakefile
    - '*.gemspec'
  DisplayCopNames: true

Metrics/LineLength:
  Enabled: false
  # IgnoreComments: true -- somehow did not recognized?..

Metrics/MethodLength:
  Max: 12

Metrics/ClassLength:
  Max: 120

# I'm big fan of and/or for flow control
Style/AndOr:
  Enabled: false

# Somehow he didn't recognize that module TimeMath is documented...
Style/Documentation:
  Enabled: false

# Everything else is just my personal style
Style/SingleLineBlockParams:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/ParallelAssignment:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
