AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'spec/*'
    - 'spec/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true

Metrics/LineLength:
  Enabled: false
  # IgnoreComments: true -- somehow did not recognized?..

# I'm big fan of and/or for flow control
Style/AndOr:
  Enabled: false

# I'm working on it!
Style/Documentation:
  Enabled: false

# Everything else is just my personal style
Style/SingleLineBlockParams:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/ParallelAssignment:
  Enabled: false
