cache: bundler
language: ruby
rvm:
  - "2.1"
  - "2.2"
  - "2.3.0"
  - jruby-9.1.6.0
  - rbx-2
matrix:
  # Doesn't play well with Rubocop
  # ...and have utterly strange ideas about timezone preservation
  allow_failures:
    - rvm: rbx-2
install:
  - bundle install --retry=3
script:
  - bundle exec rspec
  - bundle exec rubocop
