cache: bundler
language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1"
  - "2.2"
  - "2.3.0"
  - jruby-19mode
  - rbx-2
matrix:
  # Doesn't play well with Rubocop
  # ...and have utterly strange ideas about timezone preservation
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-19mode
install:
  - bundle install --retry=3
before_script:
  - export TZ=Europe/Kiev
script:
  - bundle exec rspec
  - bundle exec rubocop
